#FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5
FROM quay.io/quarkus/quarkus-micro-image:1.0

WORKDIR /work/

RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root build/native/nativeCompile/cadastral-data-disposal /work/application

EXPOSE 8080
USER 1001

CMD ["./application"]